### ISSUE TITLE
published with empty `.d.ts` file

### ISSUE THREAD

**Issue by patrick-lienau** [rickyplouis/distance-from#6]
Hi @rickyplouis, I've found your package quite useful but unfortunately, the latest version published to NPM has an empty `.d.ts` file. By this, I mean that when I import your package into my project, I get the following error:

```sh
This expression is not callable.
[dev-server] Type 'typeof import("/path-to-project/node_modules/distance-from/dist/index")' has no call signatures.
```

When I open `./node_modules/distance-from/dist/index.d.ts` I find that your package is shipping with this `.d.ts` file:
```ts
export {};
```

I think this may be because of your use of es6 style imports (eg: `import foo from 'bar';`) with your commonjs style exports (eg: `module.exports =  function (val: Position) { return new DistanceFrom(val); }` but I may be wrong. If you're are able to correct this issue, I would also ask that your export the `Position` and `Units` types (in the `.d.ts` file) so that projects consuming your package can use them in their own type definitions.

If you see this message and don't have the time to resolve the issue but could merge a PR and publish the new version, I would be happy to create a PR. Otherwise, I'll probably just end up forking this repo. Many thanks!!

**Comment by rickyplouis** [comment]
https://github.com/rickyplouis/distance-from/pull/7
